### PR TITLE
NOJIRA: Add X-BNET test race data

### PR DESCRIPTION
**Pull request by PauliusLozys**
Adds X-BNET samples from dev database in `/X-BNET` folder

### CODE REVIEW

**Comment by davseby** [comment]
Isn't the test data the same as PA? Perhaps, we can reuse it?

**Comment by PauliusLozys** [comment]
> Isn't the test data the same as PA? Perhaps, we can reuse it?

It is identical, but since XBNET provided this data, I think we should keep it for the sake of completeness.

**Comment by PauliusLozys** [comment]
Moved shared/provided data to `ProvidedData` and actual sample data to `X-BNET/ARC` folders. Added more sample for `XBNET`.

**Review by davseby — APPROVED** [review]
`ProvidedData` -> `shared`? The folder is named `testdata` itself, we're kinda stuttering here.

**Pull request merged**
